name = "FewShotAnomalyDetection"
uuid = "b4ceb2a0-2ec9-11e9-33d8-bb6e5932b8f0"
authors = ["honzabim <honzabim@gmail.com>"]
version = "0.1.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
DiffRules = "b552c78f-8df3-52c6-915a-8e097449b14b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
EvalCurves = "f38dcc0d-dce9-59d8-8cbc-ed225c093724"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
FluxExtensions = "76425322-8995-11e8-0106-93ec95767fb2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
